Repository taku-project/taku-frontend, pull requests merged in 2024-12, with the labels that each got.

#2 feat: 초기 라우팅 설정 추가
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/pages/FallbackPage.tsx
  src/pages/MainPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignUpPage.tsx
  src/pages/community/CommunityCategoryPage.tsx
  src/pages/community/CommunityDetailPage.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/community/CreateCommunityPage.tsx
  src/pages/community/UpdateCommunityPage.tsx
  src/pages/market/CreateMarketPage.tsx
  src/pages/market/MarketDetailPage.tsx
  src/pages/market/MarketPage.tsx
  src/pages/market/UpdateMarketPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/shorts/CreateShortsPage.tsx
  src/pages/shorts/ShortsPage.tsx
  src/routes.tsx
  vite.config.ts
Labels: ✨ Feat

#3 fix: package-lock json 파일 윈도우 오류 수정
  package-lock.json
Labels: 🐛 Bugfix

#14 feat: shadcn ui 컴포넌트 로드
  .storybook/preview.ts
  package-lock.json
  package.json
  postcss.config.mjs
  src/components/ui/alert-dialog.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/carousel.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  src/components/ui/progress.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/slider.tsx
  src/components/ui/sonner.tsx
  src/components/ui/switch.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/tooltip.tsx
  src/hooks/use-toast.ts
  src/stories/Button.stories.ts
Labels: 🎨 Design

#15 feat:기본 레이아웃 설정 및 임시 로딩창
  src/App.tsx
  src/assets/logo_icon.png
  src/components/loading/LoadingSpinner.tsx
  src/components/loading/index.tsx
  src/layout/DefaultLayout.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/Main.tsx
  src/routes.tsx
  src/routes/index.tsx
  src/routes/routes.tsx
Labels: ✨ Feat
